### ISSUE TITLE
Spring Boot - The bean 'dataSource' could not be injected as a 'MyDataSourceWrapper' because it is a JDK dynamic proxy that implements:

### ISSUE THREAD

**Issue by h920526** [javamelody/javamelody#695] opened 2017-11-14 01:17 UTC
hi team:

I have a same issue like this (https://github.com/javamelody/javamelody/issues/666),
And I try
`javamelody.advisor-auto-proxy-creator-enabled=false`

but it does't work for me,
Here is my code.

Application.java
```
@SpringBootApplication
@ConfigurationProperties("file:config/application.properties")
@PropertySource("file:config/config.properties")
@EnableAspectJAutoProxy
@EnableCaching
@EnableScheduling
@EnableTransactionManagement
public class Application implements SchedulingConfigurer {

    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }

    @Bean(destroyMethod = "close")
    public DataSource dataSource() {
        return new MyDataSourceWrapper();
    }

    @Bean
    public PlatformTransactionManager transactionManager(DataSource dataSource) {
        return new DataSourceTransactionManager(dataSource);
    }

    @Bean
    public NamedParameterJdbcTemplate namedParameterJdbcTemplate(DataSource dataSource) {
        return new NamedParameterJdbcTemplate(dataSource);
    }
}
```

application.properties
```
javamelody.enabled=true
javamelody.init-parameters.authorized-users=admin:123
javamelody.advisor-auto-proxy-creator-enabled=false
```

```
The bean 'dataSource' could not be injected as a 'wrapper.MyDataSourceWrapper' because it is a JDK dynamic proxy that implements:
	javax.sql.DataSource
	java.lang.AutoCloseable
```

Env:
JDK 1.8.0_111
Win7 64bit
'org.springframework.boot:spring-boot-starter-web:1.5.8.RELEASE',
'org.springframework.boot:spring-boot-starter-aop:1.5.8.RELEASE',
'net.bull.javamelody:javamelody-spring-boot-starter:1.69.0',

thanks a lot

**Comment by evernat** [comment] 2017-11-16 00:03
Can you give the source of a runnable project to reproduce the issue?
Thanks.

**Comment by h920526** [comment] 2017-11-16 01:20
Hi evernat:

Here is my source code,
thanks for your help.

[gradle_project.zip](https://github.com/javamelody/javamelody/files/1476967/gradle_project.zip)

**Comment by evernat** [comment] 2017-11-16 22:05
Ok, I understand the issue and it's not the same as #666.
In fact, javamelody [creates a proxy with SpringDataSourceBeanPostProcessor](https://github.com/javamelody/javamelody/blob/master/javamelody-spring-boot-starter/src/main/java/net/bull/javamelody/JavaMelodyAutoConfiguration.java#L160) to monitor jdbc connections and sql requests. Then the proxy of type DataSource can't be injected as MyDataSourceWrapper.

But first, I don't understand why you use MyDataSourceWrapper. You could return and use HikariDataSource directly. Why do you create a MyDataSourceWrapper?
Then why injecting the datasource as MyDataSourceWrapper instead of injecting as javax.sql.DataSource? You are linking your code to a specific wrapper instead of being dependent on `javax.sql.DataSource` only, like if your wrapper is transparent. If you insist on this, you may better inject as javax.sql.DataSource and use datasource.unwrap when needed.

If you insist on doing both the above, you can fix the issue by adding `javamelody.excluded-datasources=dataSource` in your `application.properties` file, at the price of disabling the monitoring of jdbc connections and of sql requests.

Closing as not a bug.

**Closed by evernat** 2017-11-16 22:05 UTC

**Comment by sasconsul** [comment] 2018-03-30 00:10
Losing the ability to monitor JDBC connections and SQL requests is a biggie.  I vote for this being a bug when interfacing with JavaMelody.

**Comment by rohantilekar** [comment] 2019-11-12 15:57
add this in your main application file under SpringBootApplication
@SpringBootApplication
@EnableCaching(proxyTargetClass = true)

**Comment by TouSS** [comment] 2019-12-26 02:39
I have the same question when I extend AbstractRoutingDataSource to deal with multi datasources
