### ISSUE TITLE
can not set logger by myself

### ISSUE THREAD

**Issue by Foxswily** [javamelody/javamelody#566] opened 2016-08-13 09:34 UTC
Version: 1.59.0
JDK:1.7.0_70
Tomcat:7.0.x

--------------------
Background: There is a log4j-1.x.jar in ${CATALINA_BASE}/lib which means tomcat log uses log4j to write log and my context can find log4j classes. My own application uses slf4j + logback.
When I put myapp.war into tomcat,an exception is thrown out

```java
java.lang.NoSuchMethodError: net.bull.javamelody.Log4JAppender.setThreshold(Lorg/apache/log4j/Priority;)V
       	at net.bull.javamelody.Log4JAppender.<init>(Log4JAppender.java:42)
       	at net.bull.javamelody.Log4JAppender.<clinit>(Log4JAppender.java:34)
       	at net.bull.javamelody.FilterContext.initLogs(FilterContext.java:283)
       	at net.bull.javamelody.FilterContext.<init>(FilterContext.java:70)
```
I found that there is a param called `logger-class` can be set, I've done it and failed.

I added this to web.xml, got the same exception

```java
<context-param>
	<param-name>javamelody.logger-class</param-name>
	<param-value>net.bull.javamelody.LogbackLogger</param-value>
</context-param>
```

I found codes in `FilterContext.java`

```java
	private static void initLogs() {
		// on branche le handler java.util.logging pour le counter de logs
		LoggingHandler.getSingleton().register();

		if (LOG.LOGBACK_ENABLED) {
			// si logback est disponible on branche aussi l'appender pour le counter de logs
			LogbackAppender.getSingleton().register();
		}

		if (LOG.LOG4J_ENABLED) {
			// si log4j est disponible on branche aussi l'appender pour le counter de logs
			Log4JAppender.getSingleton().register();
		}

		if (LOG.LOG4J2_ENABLED) {
			// si log4j2 est disponible on branche aussi l'appender pour le counter de logs
			Log4J2Appender.getSingleton().register();
		}

		LOG.debug("log listeners initialized");
	}
```

Is there any way to set logger by myself or I missed something ?

Thanks for reply.

**Comment by evernat** [comment] 2016-08-16 23:00
The logger-class parameter is used when javamelody is logging, and not in this case when registering listeners for messages logged by the application. So the logger-class parameter can not help you in this case.
So I suggest that you look jars which contains log4j classes such as log4j* and slf4j*.
Or if you give the source of a simple project (using maven if possible) + tomcat/lib to reproduce the issue, I will look for the root cause.
Anyway, let me know what we can do with this issue.

**Comment by Foxswily** [comment] 2016-08-22 14:52
I made a simple test to reproduce this issue [jmtest.zip](https://github.com/javamelody/javamelody/files/430429/jmtest.zip)
And you can follow this [doc](https://tomcat.apache.org/tomcat-7.0-doc/logging.html#Using_Log4j) to config tomcat + log4j 
logfile: tomcat/logs/localhost

```
java.lang.NoSuchMethodError: net.bull.javamelody.Log4JAppender.setThreshold(Lorg/apache/log4j/Priority;)V
       	at net.bull.javamelody.Log4JAppender.<init>(Log4JAppender.java:42)
       	at net.bull.javamelody.Log4JAppender.<clinit>(Log4JAppender.java:34)
       	at net.bull.javamelody.FilterContext.initLogs(FilterContext.java:283)
       	at net.bull.javamelody.FilterContext.<init>(FilterContext.java:70)
       	at net.bull.javamelody.MonitoringFilter.init(MonitoringFilter.java:112)
       	at org.apache.catalina.core.ApplicationFilterConfig.initFilter(ApplicationFilterConfig.java:279)
```

**Comment by evernat** [comment] 2016-08-28 13:14
I have reproduced the issue.
But first, you include in the webapp log4j-over-slf4j.jar which contains empty log4j classes and you include log4j.jar in tomcat/lib which of cource contains log4j classes. The clash between two versions of Log4J classes can ask for problems.

Anyway, the problem is that your webapp includes old versions of log4j-over-slf4j and of slf4j-api. Upgrade them to the latest versions (1.7.21) and your issue is gone.
In fact, the issue was fixed by Slf4J here:
https://github.com/qos-ch/slf4j/commit/fd4ce7947ba9e223670f22ee932020e767428c81#diff-5799ce79ad50348887976edbc73cb38d

**Closed by evernat** 2016-08-28 13:14 UTC
