### ISSUE TITLE
JavaMelody JDBC monitorization and ServletContextListener with database access.

### ISSUE THREAD

**Issue by Zidedine** [javamelody/javamelody#612] opened 2017-02-15 19:35 UTC
Hi,

I  have a Java application deployed in a Tomcat.
This application has a ServletContextListener wich loads on the startup of the application. 
This listener, on the contextInitialized event, stores data in a database. On contextDestroyed it deletes the data stored during the startup.

We use JavaMelody with SQL monitorization. Sometimes, we get an error in net.bull.javamelody.JdbcWrapper.

```
***Information about encapsulated exception***
java.lang.NullPointerException
	at net.bull.javamelody.JdbcWrapper.doExecute(JdbcWrapper.java:392)
	at net.bull.javamelody.JdbcWrapper$StatementInvocationHandler.invoke(JdbcWrapper.java:134)
	at net.bull.javamelody.JdbcWrapper$DelegatingInvocationHandler.invoke(JdbcWrapper.java:291)
	at oracle.jdbc.driver.$Proxy99.execute(Unknown Source)
```

Is JavaMelody incompatible with own ServletContextListeners defined in the application monitorized?
Is a problem with de listener's initialization order? 

We have this configuration in web.xml

```
<!-- My own listener with database operations -->
<listener>
  <listener-class>
    es.monitorizacion.listener.MyRegisterListener
  </listener-class> 
</listener>

<!-- JavaMelody configuration-->
<filter>
    <filter-name>monitoring</filter-name>
    <filter-class>net.bull.javamelody.MonitoringFilter</filter-class>
 	<init-param>
		<param-name>datasources</param-name>
		<param-value>java:comp/env/jdbc/miAplicacion</param-value>
	</init-param>
</filter>

<filter-mapping>
	<filter-name>monitoring</filter-name>
    <url-pattern>/*</url-pattern>
</filter-mapping>

<listener>
	<listener-class>net.bull.javamelody.SessionListener</listener-class>
</listener>

```

**Comment by evernat** [comment] 2017-02-17 22:47
Yes, javamelody is supposed to be compatible with your own ServletContextListeners defined in the application monitorized.
What is the javamelody version you are using?
Can you give the complete stack-trace of the NullPointerException?

And can you debug in a IDE the net.bull.javamelody.JdbcWrapper class at line 392 for NullPointerException or give the source of a project (using Maven if possible) to reproduce the issue? (Because I don't understand what object is null and can cause a NullPointerException.)

**Comment by Zidedine** [comment] 2017-02-18 11:52
Version: JavaMelody 1.53

Sorry, but we can't share the source code of our organization. 
I'll try with the debug. This is the complete stacktrace of the error:

```
[09-feb-2017 13:01:22,327] FATAL [main::es.myorganization.core.monitorizacionfacade.MonitorizacionFacade::deleteInfoBD::74] -> 
es.myorganization.utils.excepcions.FatalErrorException
    at es.myorganization.utils.accions.ProcesadorActions.procesa(ProcesadorActions.java:158)
    at es.myorganization.core.monitorizacionfacade.MonitorizacionFacade.deleteInfoBD(MonitorizacionFacade.java:71)
    at es.myorganization.util.monitorizacion.listener.MyRegisterListener.contextDestroyed(MyRegisterListener.java:59)
    at org.apache.catalina.core.StandardContext.listenerStop(StandardContext.java:4174)
    at org.apache.catalina.core.StandardContext.stop(StandardContext.java:4778)
    at org.apache.catalina.core.ContainerBase.removeChild(ContainerBase.java:924)
    at org.apache.catalina.startup.HostConfig.undeployApps(HostConfig.java:1319)
    at org.apache.catalina.startup.HostConfig.stop(HostConfig.java:1290)
    at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:323)
    at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:119)
    at org.apache.catalina.core.ContainerBase.stop(ContainerBase.java:1086)
    at org.apache.catalina.core.ContainerBase.stop(ContainerBase.java:1098)
    at org.apache.catalina.core.StandardEngine.stop(StandardEngine.java:450)
    at org.apache.catalina.core.StandardService.stop(StandardService.java:587)
    at org.apache.catalina.core.StandardServer.stop(StandardServer.java:744)
    at org.apache.catalina.startup.Catalina.stop(Catalina.java:648)
    at org.apache.catalina.startup.Catalina.start(Catalina.java:615)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:289)
    at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:414)
***Information about encapsulated exception***
java.lang.NullPointerException
    at net.bull.javamelody.JdbcWrapper.doExecute(JdbcWrapper.java:392)
    at net.bull.javamelody.JdbcWrapper$StatementInvocationHandler.invoke(JdbcWrapper.java:134)
    at net.bull.javamelody.JdbcWrapper$DelegatingInvocationHandler.invoke(JdbcWrapper.java:291)
    at oracle.jdbc.driver.$Proxy99.execute(Unknown Source)
    at es.myorganization.utils.GestorConexiones.setNlsOrder(GestorConexiones.java:341)
    at es.myorganization.utils.GestorConexiones.getConexionBD(GestorConexiones.java:167)
    at es.myorganization.utils.GestorConexionesJNDI.getConexionBD(GestorConexionesJNDI.java:21)
    at es.myorganization.utils.UtilidadesCore.getConexionBD(UtilidadesCore.java:384)
    at es.myorganization.core.xmldao.CoreXmlDaoUtilidades.getConexionBD(CoreXmlDaoUtilidades.java:149)
    at es.myorganization.xmldao.impl.ConnectionHolder.createWriteConnection(ConnectionHolder.java:166)
    at es.myorganization.xmldao.Transaction.<init>(Transaction.java:79)
    at es.myorganization.utils.accions.ProcesadorActions.procesa(ProcesadorActions.java:131)
    at es.myorganization.core.monitorizacionfacade.MonitorizacionFacade.deleteInfoBD(MonitorizacionFacade.java:71)
    at es.myorganization.util.monitorizacion.listener.MyRegisterListener.contextDestroyed(MyRegisterListener.java:59)
    at org.apache.catalina.core.StandardContext.listenerStop(StandardContext.java:4174)
    at org.apache.catalina.core.StandardContext.stop(StandardContext.java:4778)
    at org.apache.catalina.core.ContainerBase.removeChild(ContainerBase.java:924)
    at org.apache.catalina.startup.HostConfig.undeployApps(HostConfig.java:1319)
    at org.apache.catalina.startup.HostConfig.stop(HostConfig.java:1290)
    at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:323)
    at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:119)
    at org.apache.catalina.core.ContainerBase.stop(ContainerBase.java:1086)
    at org.apache.catalina.core.ContainerBase.stop(ContainerBase.java:1098)
    at org.apache.catalina.core.StandardEngine.stop(StandardEngine.java:450)
    at org.apache.catalina.core.StandardService.stop(StandardService.java:587)
    at org.apache.catalina.core.StandardServer.stop(StandardServer.java:744)
    at org.apache.catalina.startup.Catalina.stop(Catalina.java:648)
    at org.apache.catalina.startup.Catalina.start(Catalina.java:615)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:289)
    at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:414)
[09-feb-2017 13:01:22,367] ERROR [main::es.myorganization.util.monitorizacion.listener.MyRegisterListener::contextDestroyed::62] -> Problema: null
```

**Comment by evernat** [comment] 2017-02-18 12:58
Thanks for the stack-trace.
I am not sure that your javamelody version is 1.53 because there is nothing in that version at line 392 in JdbcWrapper.java where the NullPointerException is thrown:
https://github.com/javamelody/javamelody/blob/javamelody-core-1.53.0/javamelody-core/src/main/java/net/bull/javamelody/JdbcWrapper.java#L392

**Comment by Zidedine** [comment] 2017-02-20 07:25
Sorry, my mistake. The version is JavaMelody 1.63.

https://github.com/javamelody/javamelody/blob/javamelody-core-1.63.0/javamelody-core/src/main/java/net/bull/javamelody/JdbcWrapper.java#L392

**Comment by evernat** [comment] 2017-03-17 18:17
As said before
> can you debug in a IDE the net.bull.javamelody.JdbcWrapper class at line 392 for NullPointerException or give the source of a project (using Maven if possible) to reproduce the issue? (Because I don't understand what object is null and can cause a NullPointerException.)

Any news?

**Comment by Zidedine** [comment] 2017-03-17 19:10
No news. We couldn't reproduce the error.
It's a random error, it only appears sometimes when we redeploy our j2ee app in a tomcat and the listener starts.

**Comment by evernat** [comment] 2017-03-17 19:37
And given the stack-trace above, the exception is when initializing a jdbc connection while stopping the webapp in a listener.

Thanks for your last informations. Closing if no more information.
The issue can be reopened easily if needed.

**Closed by evernat** 2017-03-17 19:37 UTC
