### ISSUE TITLE
CounterReponseStream throws IllegalStateException when using Java 8 and tomcat 8

### ISSUE THREAD

**Issue by cjnoyescrisp** [javamelody/javamelody#526] opened 2016-01-07 15:51 UTC
Jan 07, 2016 10:47:21 AM org.apache.catalina.core.StandardWrapperValve invoke
SEVERE: Servlet.service() for servlet [ads] in context with path [/ads-webapp] threw exception [Request processing failed; nested exception is java.lang.IllegalStateException: getWriter() has already been called for this response] with root cause
java.lang.IllegalStateException: getWriter() has already been called for this response
	at org.apache.catalina.connector.Response.getOutputStream(Response.java:545)
	at org.apache.catalina.connector.ResponseFacade.getOutputStream(ResponseFacade.java:195)
	at javax.servlet.ServletResponseWrapper.getOutputStream(ServletResponseWrapper.java:100)
	at javax.servlet.ServletResponseWrapper.getOutputStream(ServletResponseWrapper.java:100)
	at net.bull.javamelody.CounterResponseStream.<init>(CounterResponseStream.java:38)
	at net.bull.javamelody.CounterServletResponseWrapper.createOutputStream(CounterServletResponseWrapper.java:75)
	at net.bull.javamelody.FilterServletResponseWrapper.getOutputStream(FilterServletResponseWrapper.java:109)
	at net.bull.javamelody.FilterServletResponseWrapper.getWriter(FilterServletResponseWrapper.java:124)

This is with javamelody core 1.58.0

Works fine with Java 7

Also the url that caused this error is not the monitoring url

java melody works fine when you go to the monitoring url

**Comment by evernat** [comment] 2016-01-07 20:37
Can you give the source of a simple project (using Maven if possible) to reproduce the issue?

**Comment by cjnoyescrisp** [comment] 2016-01-07 20:50
Let me work on it. The issue surfaced with an existing application, just
switching runtimes.
The application uses Spring framework and Spring security which I think is
going to be the minimal

**Comment by cjnoyescrisp** [comment] 2016-01-12 15:57
I found the source of the problem. My application has a filter that uses a class that extends HttpServletResponseWrapper that was written to capture text using a CharArrayWriter, I normally only use the getWriter() method, you use getOutputStream(), which I didn't override for your CapturingResponseWrapper.getOutputStream() line: 25	
CounterResponseStream.<init>(HttpServletResponse) line: 38	
CounterServletResponseWrapper.createOutputStream() line: 75	
CounterServletResponseWrapper(FilterServletResponseWrapper).getOutputStream() line: 109	
CounterServletResponseWrapper(FilterServletResponseWrapper).getWriter() line: 124

It is my expectation that your monitor calls, won't attempt to, or prepare to write output unless I am calling the /monitoring path

**Comment by evernat** [comment] 2016-01-12 17:37
First, for "It is my expectation that your monitor calls, won't attempt to, or prepare to write output unless I am calling the /monitoring path": in fact, javamelody does not prepare to write output, it only uses a HttpServletResponseWrapper and overrides outputStream or writer to *count bytes written by your app* for all monitored URLs.

Then, it seems that you are not using javamelody 1.58.0, because the line numbers in your stack-trace does not match with the line numbers of javamelody 1.58.0 which can be seen here:
https://github.com/javamelody/javamelody/blob/javamelody-core-1.58.0/javamelody-core/src/main/java/net/bull/javamelody/FilterServletResponseWrapper.java

In fact, given your line numbers it seems that you are using javamelody 1.56.0 or before.
That's unfortunate because if you were really using javamelody 1.58, you will have the fix for issue 488, which fixes exactly your case (a filter in your app which calls getWriter() before the MonitoringFilter).
So I suggest to check what is deployed on your server and for example which version of the javamelody jar file is in the WEB-INF/lib directory of the war file of your app (or otherwise in the tomcat/lib directory of your server).

Please confirm us about it, so that we can close this issue as duplicate of #488 .

**Comment by cjnoyescrisp** [comment] 2016-01-12 17:44
Sorry about the confusion, I figured out the version issue after I wrote,
once Updating the version, things worked after I backed out the attempts I
made to solve the problem. This can be closed as duplicate

**Comment by evernat** [comment] 2016-01-12 20:44
thanks, closing as duplicate of #488

**Closed by evernat** 2016-01-12 20:44 UTC
Labels: duplicate
