### ISSUE TITLE
Need path variables in the request URL

### ISSUE THREAD

**Issue by rachitbshephertz** [javamelody/javamelody#923] opened 2020-06-24 08:36 UTC
I have Integrated the java melody with my spring project. 

Below is the request path that is captured.
"/handler{env}/{bankid}/{channelName}/{servicegrp}/{apiname}/** POST"

I need it to be the actual path with values like
"/handlersb/1/synch/main/send/** POST"
 
Any help will be highly appreciated. Thanks in advance.

**Comment by evernat** [comment] 2020-06-24 10:46
The request paths according spring mvc request mappings like `/handler{env}/{bankid}/{channelName}/{servicegrp}/{apiname}/** POST` works as intended, in order to aggregate requests in statistics and so to not have too much used space on disk.
You can't have the values such as bankid of all the requests. So closing as invalid.

That said, if all you want is for example the value `send` in the statistics separated from apiname values, you may duplicate your methods for all possible values.
For example, you may change something like:
```java
@PostMapping("/handlersb/{bankid}/synch/main/{apiname}/**")
public void transfer(@PathVariable("bankid") String bankid, @PathVariable("apiname") apiname) {
  this.transferToApi(bankid, apiname);
}
```
to something like:
```java
@PostMapping("/handlersb/{bankid}/synch/main/send/**")
public void transfer(@PathVariable("bankid") String bankid) {
  this.transferToApi(bankid, "send");
}
@PostMapping("/handlersb/{bankid}/synch/main/receive/**")
public void transfer(@PathVariable("bankid") String bankid) {
  this.transferToApi(bankid, "receive");
}
```

**Closed by evernat** 2020-06-24 10:46 UTC

**Comment by rachitbshephertz** [comment] 2020-06-24 13:47
Thanks for getting back quickly. Actually all these values are dynamic and can not be made static. Is there a way where I can extend the current javamelody logic to meet my needs. Since I won't be having an issue related to disk because this is the only endpoint my application exposes and type of variables are limited.  

This feature is going to be a part of a huge project and can not move forward without this. I know it does not concern you but as I said Any help will be highly appreciated.
