### ISSUE TITLE
JavaMelody using LDAP/Active Directory authentication works unexpected

### ISSUE THREAD

**Issue by clauswit** [javamelody/javamelody#656] opened 2017-08-02 14:07 UTC
Hi,

we have integrated our Java Melody in our Tomcat and activated LDAP/AD Authentication.

This works fine if I try to access my server like 
http://servername:port/monitoring

I get one single authentication query and I have no problem.

When I try to access my monitoring for a single webapp (as root will not show information I need) like
http://servername:port/mywebapp/monitoring

I get multiple (twenty or thirty) authentication queries for accessing this site.
If I cancel the first one - no access (as it should be), if i cancel any of the other authentication queries - some of the images like CPU or active JDBC Sessions won't show up.
I get same procedure for every "image" I try to enter...

For every "authenticaten cancel" I get the following message in my Log:

`javax.naming.CommunicationException: connection closed [Root exception is java.io.IOException: connection closed]; remaining name 'dc=bghw,dc=de'
       at com.sun.jndi.ldap.LdapCtx.doSearch(LdapCtx.java:2014)
       at com.sun.jndi.ldap.LdapCtx.searchAux(LdapCtx.java:1856)
       at com.sun.jndi.ldap.LdapCtx.c_search(LdapCtx.java:1781)
       at com.sun.jndi.toolkit.ctx.ComponentDirContext.p_search(ComponentDirContext.java:404)
       at com.sun.jndi.toolkit.ctx.PartialCompositeDirContext.search(PartialCompositeDirContext.java:370)
       at com.sun.jndi.toolkit.ctx.PartialCompositeDirContext.search(PartialCompositeDirContext.java:353)
       at javax.naming.directory.InitialDirContext.search(InitialDirContext.java:278)
       at org.apache.catalina.realm.JNDIRealm.getUserBySearch(JNDIRealm.java:1655)
       at org.apache.catalina.realm.JNDIRealm.getUser(JNDIRealm.java:1491)
       at org.apache.catalina.realm.JNDIRealm.getUser(JNDIRealm.java:1439)
       at org.apache.catalina.realm.JNDIRealm.authenticate(JNDIRealm.java:1380)
       at org.apache.catalina.realm.JNDIRealm.authenticate(JNDIRealm.java:1285)
       at org.apache.catalina.realm.EncryptedJNDIRealm.authenticate(EncryptedJNDIRealm.java:108)
       at org.apache.catalina.authenticator.BasicAuthenticator.authenticate(BasicAuthenticator.java:84)
       at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:577)
       at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
       at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
       at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
       at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
       at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:509)
       at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1104)
       at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:684)
       at org.apache.tomcat.util.net.Nio2Endpoint$SocketProcessor.doRun(Nio2Endpoint.java:1092)
       at org.apache.tomcat.util.net.Nio2Endpoint$SocketProcessor.run(Nio2Endpoint.java:1051)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1153)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
       at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
       at java.lang.Thread.run(Thread.java:785)
 Caused by: java.io.IOException: connection closed
       at com.sun.jndi.ldap.LdapClient.ensureOpen(LdapClient.java:1604)
       at com.sun.jndi.ldap.LdapClient.search(LdapClient.java:542)
       at com.sun.jndi.ldap.LdapCtx.doSearch(LdapCtx.java:1997)
       ... 27 more`

As we are not allowed to store unencrypted Passwords on our Server we have implemented an Overwrite Class `EncryptedJNDIRealm` which will do this for us.
As all of this works fine on root-monitoring I guess this has nothing to do with our Problem?!

Additionally: If I use tomcat internal user database instead - no problem at all.

**Comment by clauswit** [comment] 2017-08-02 14:08
I am on Holiday for two weeks now. So do not close ticket before ;-)

**Comment by evernat** [comment] 2017-08-07 21:11
Are you sure that there is a difference between the root monitoring path and the mywebapp monitoring path ? Perhaps you had a http session created before testing the root monitoring path ? If you still reproduce the same behavior again, I don't know why there is a difference between the two path. It certainly depends of the implementation of the Tomcat realm and not on javamelody, because the reports only calls urls from the browser.

To fix the issue, I would suggest to always have an http session existing before authenticating, then the realm should cache in the session the fact that the user is authenticated. I think that it can be done by adding `alwaysUseSession="true"`. I have not tried it, but it seems you need an authenticator for `alwaysUseSession` like a [BasicAuthenticator](https://tomcat.apache.org/tomcat-7.0-doc/config/valve.html#Basic_Authenticator_Valve) inside a `Context` (in conf/server.xml or in conf/Catalina/localhost/mywebapp.xml).

**Comment by evernat** [comment] 2017-09-06 22:13
any news?

**Comment by clauswit** [comment] 2017-09-07 21:40
Hi sorry, but I was under water with work, so I was not able to test it till now. I try it next week!

**Comment by evernat** [comment] 2017-11-22 23:56
Have you taken your breath? Any news on that?

**Comment by clauswit** [comment] 2017-11-23 15:31
Hi, 
sorry still on fire :-)
Maybe you missunderstood me. I do not get an error while I open root-monitoring.
I have this problem only if use monitoring in a subpath.
Currently I have disabled AD Auth and I use TomcatAuth without Problem. I may test this on Christmas Holiday again :-(

**Comment by kortov** [comment] 2019-10-01 11:33
@clauswit  the is issue is still valid?

**Comment by evernat** [comment] 2020-06-26 13:51
not enough information on this issue/question for a long time, so closing

**Closed by evernat** 2020-06-26 13:51 UTC
Labels: question
