### ISSUE TITLE
JavaMelody brakes Spring Boot tests

### ISSUE THREAD

**Issue by sagnik1988** [javamelody/javamelody#930] opened 2020-07-13 15:05 UTC
The application is developed on Spring Boot 2.2.0. I include the below dependency to be able to use JavaMelody -

<dependency>
			<groupId>net.bull.javamelody</groupId>
			<artifactId>javamelody-spring-boot-starter</artifactId>
			<version>1.81.0</version>
		</dependency>

And the application.properties are like below: (Using a management port which is separate from application port to show monitoring report).

server.port=8084
management.server.port: 8081
javamelody.enabled=true
javamelody.management-endpoint-monitoring-enabled=true
management.endpoints.web.exposure.include= info,health,monitoring

Integration Tests, through the Test Class annotated with @SpringBootTest is breaking. 

It can be fixed by removing javamelody dependency or by disabling javamelody in config file of the application as below :

spring.autoconfigure.exclude=net.bull.javamelody.JavaMelodyAutoConfiguration

**Comment by evernat** [comment] 2020-07-13 16:50
I do not reproduce the issue.
Do you the stack-trace of an exception?
Can you give the source of a simple project to reproduce the issue?

**Comment by evernat** [comment] 2020-07-20 09:54
any news?

**Comment by sagnik1988** [comment] 2020-07-21 07:53
Hi, I don't have a sample project read yet. I'll create one and update.

**Comment by evernat** [comment] 2020-08-01 22:13
any news?

**Comment by aresnick-ATPCO** [comment] 2020-08-07 17:25
From what I see in the maven repository, even the latest javamelody (1.85) isn't 100% compatible with SpringBoot 2.2.0; looks like there are spring-boot-starter-app-aop (and hence javassist/spring-aop) 2.1.x dependencies in it.

https://mvnrepository.com/artifact/net.bull.javamelody/javamelody-spring-boot-starter/1.85.0

For us, these dependencies prevented our app from successfully starting unless we turned off aop byte code verification using the jvm -Xverify:none argument.  You also could see if/how well you could solve your issues (assuming your using maven) through maven (or other build tools) dependency exclusions.

evernat - can you speak to the apparent SpringBoot 2.1.x javamelody dependencies and if/when a fully Boot 2.2.0 compatible javamelody version might be released?

**Comment by evernat** [comment] 2020-08-08 12:11
I maintain javamelody-spring-boot-starter so you speak to the right person.

First mvnrepository.com is not the maven repository as you suggest. mvnrepository.com just displays ads for money with data from other sources.
The source of truth is Maven Central in which you can search at https://search.maven.org/

Then, yes, javamelody-spring-boot-starter has a dependency on spring-boot-starter-aop and so on spring-aop.
I see that as normal in Sprint Boot 2, for javamelody which benefits from interceptors and AOP like many features in Spring Boot. There is no plan to change that.

For your case, I don't know if there is an issue or another workaround in your tests or in javamelody and I do not have a sample project to reproduce.
I would think that `spring.autoconfigure.exclude=net.bull.javamelody.JavaMelodyAutoConfiguration` as you said, in configuration of tests would be simpler than adding `-Xverify:none`, but I can't see without a sample.

Do we close this?

**Comment by evernat** [comment] 2020-09-21 19:58
No response from the reporter and no project to reproduce, so closing.

**Closed by evernat** 2020-09-21 19:58 UTC
