### ISSUE TITLE
Only from one instance is collecting data using MonitoringFilter.registerApplicationNodeInCollectServer

### ISSUE THREAD

**Issue by enavarrocu** [javamelody/javamelody#910] opened 2020-04-29 23:14 UTC
Hello, 

I'm deploying 3 instances of the same web application on different servers. The application register itself using `MonitoringFilter.registerApplicationNodeInCollectServer`. It reads one time from each server, after that only read from only one server. Any idea what can I be doing wrong?

Thanks in advance

**Comment by evernat** [comment] 2020-05-02 23:29
Hello,
It seems that you are using the optional collect server.
Just to check, what makes you say that it only read from only one server after the first reads?
Then what are the javamelody versions in the webapp and in the collect server?
And what are the parameters in the 3 calls to `MonitoringFilter.registerApplicationNodeInCollectServer` (without private information)?
Do you use the same applicationName each time?
Do you use the same applicationNodeUrl each time?

**Comment by enavarrocu** [comment] 2020-05-03 10:36
Hello @evernat,

Thank you for answering. Yes, I'm using the optional collect server. Both versions are the same, `1.82.0`. I do use the same `applicationName` each time, it's the same application deployed in two different machines. The `applicationNodeUrl` is not the same because each node has a different IP address. More details below.

**Node1:** registerApplicationNodeInCollectServer("CSS", "http://host.docker.internal:9999", "http://monitoring:monitoring@192.168.128.5:8080/CSS");

**Node2:** registerApplicationNodeInCollectServer("CSS", "http://host.docker.internal:9999", "http://monitoring:monitoring@192.168.128.4:8080/CSS");

[javamelody.log](https://github.com/javamelody/javamelody/files/4570053/javamelody.log)

As you can see in the image only one node stay there registered.
<img width="1211" alt="Screenshot 2020-05-03 at 12 31 19" src="https://user-images.githubusercontent.com/318491/80911959-0afa0b00-8d3a-11ea-8ac2-89321592e07f.png">

Thank you for taking a look.

**Comment by evernat** [comment] 2020-05-03 18:24
I think that this issue is related to synchronization, related to the duration of the first collect, when using MonitoringFilter.registerApplicationNodeInCollectServer in several instances started at the same time. The cause of the long duration (12 seconds) of the first collect may be that the webapps are not yet fully started.
The issue should be fixed by (86735ed) and ready for the next release (1.83). I have made a snapshot build of the collect server and it is available at http://javamelody.org/downloads/javamelody-collector-server-1.83.0-SNAPSHOT.war
Can you say if the snapshot build is ok for you?

**Comment by enavarrocu** [comment] 2020-05-03 18:37
Thank @evernat, it's working now. I will let it work for a few hours to check if working properly. For when is planned the release of 1.83?

Again thank you.

**Comment by evernat** [comment] 2020-05-03 18:46
The release is planned in a few days.
You are welcome.

**Closed by evernat** 2020-05-03 18:46 UTC
