### ISSUE TITLE
the details/statistics about the Heap Memory, like eden_space,surviver_space

### ISSUE THREAD

**Issue by meiwulang** [javamelody/javamelody#905] opened 2020-03-27 09:35 UTC
Can you add something, then  we can see the **details/statistics** about the **Heap Memory**.like Eden_space,surviver_space?

So great framework!
It can be better ,if it has **details/statistics** about the heap memory

**Comment by evernat** [comment] 2020-03-27 17:26
This was asked before.
Closing as duplicate of #182.
You can subscribe to notifications there.

**Closed by evernat** 2020-03-27 17:26 UTC
