### ISSUE TITLE
Melody causing NullPointerException when used with Spring

### ISSUE THREAD

**Issue by arranzropablo** [javamelody/javamelody#706] opened 2017-12-13 09:44 UTC
Hello,
I'm developing an application with Spring and I decided to use Java melody on it, but when using this dependency my services are correctly autowired at first but then they are set to null and I get nullpointerexceptions... Is anyone else having this problem? Thanks.

Edit: They are not even correctly Autowired at first, they have every field set to null.

**Comment by evernat** [comment] 2017-12-13 15:07
Hi,
I think that this is not a valid question, so closing as invalid.
It would be better with the source of a simple project to reproduce the issue for example.
bye

**Closed by evernat** 2017-12-13 15:07 UTC

**Comment by Richie94** [comment] 2021-01-07 14:55
FYI: I know its been a long time but we had the same issue right now, still not sure whats the cause but at least
```
javamelody.spring-monitoring-enabled=false
```
fixed it. So war we dont need monitoring beans, so its sufficient for us.

**Comment by evernat** [comment] 2021-01-10 18:21
@Richie94 
Please give at least a stack-trace or the source of a project to reproduce the issue.
