### ISSUE TITLE
Error inside melody while processing error ?

### ISSUE THREAD

**Issue by xpoinsard** [javamelody/javamelody#1052] opened 2021-11-25 11:07 UTC
Hi,
We are tracking an issue and we have many errors like the following. 
We are using javamelody 1.87.0 with Tomcat 9.0.39.
Could javamelody prevent some errors to be logged in case of invalid request ?

```
java.lang.IllegalStateException: L'objet requête a été recyclé et n'est plus associé à cette façade
        at org.apache.catalina.connector.RequestFacade.getAttribute(RequestFacade.java:279)
        at org.apache.catalina.core.ApplicationHttpRequest.getAttribute(ApplicationHttpRequest.java:246)
        at javax.servlet.ServletRequestWrapper.getAttribute(ServletRequestWrapper.java:83)
        at javax.servlet.ServletRequestWrapper.getAttribute(ServletRequestWrapper.java:83)
        at javax.servlet.ServletRequestWrapper.getAttribute(ServletRequestWrapper.java:83)
        at javax.servlet.ServletRequestWrapper.getAttribute(ServletRequestWrapper.java:83)
        at net.bull.javamelody.internal.model.CounterError.<init>(CounterError.java:78)
        at net.bull.javamelody.internal.model.Counter.addRequestForSystemError(Counter.java:562)
        at net.bull.javamelody.LoggingHandler.addErrorLogToCounter(LoggingHandler.java:80)
        at net.bull.javamelody.LoggingHandler.addErrorLogToCounter(LoggingHandler.java:74)
        at net.bull.javamelody.LoggingHandler.publish(LoggingHandler.java:117)
        at java.logging/java.util.logging.Logger.log(Logger.java:979)
        at java.logging/java.util.logging.Logger.doLog(Logger.java:1006)
        at java.logging/java.util.logging.Logger.logp(Logger.java:1283)
        at org.apache.juli.logging.DirectJDKLog.log(DirectJDKLog.java:175)
        at org.apache.juli.logging.DirectJDKLog.error(DirectJDKLog.java:141)
        at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:729)
        at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:459)
        at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:384)
        at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:312)
        at org.apache.struts.chain.commands.servlet.PerformForward.handleAsForward(PerformForward.java:113)
        at org.apache.struts.chain.commands.servlet.PerformForward.perform(PerformForward.java:96)
        at org.apache.struts.chain.commands.AbstractPerformForward.execute(AbstractPerformForward.java:54)
        at org.apache.struts.chain.commands.ActionCommandBase.execute(ActionCommandBase.java:51)
        at org.apache.commons.chain.impl.ChainBase.execute(ChainBase.java:191)
        at org.apache.commons.chain.generic.LookupCommand.execute(LookupCommand.java:305)
        at org.apache.commons.chain.impl.ChainBase.execute(ChainBase.java:191)
        at org.apache.struts.chain.ComposableRequestProcessor.process(ComposableRequestProcessor.java:283)
        at org.apache.struts.action.ActionServlet.process(ActionServlet.java:1915)
        at org.apache.struts.action.ActionServlet.doGet(ActionServlet.java:446)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:626)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
```

**Comment by evernat** [comment] 2021-11-29 00:08
I have never seen this issue before.
I confirm that javamelody is not supposed to throw an exception like this, including when logging an error.
But it seems to be Struts 1 (!) calling foward inside a get call inside Tomcat 9. Given that the issue is not seen in general and that it is Struts 1 which is better to be forgotten, we do not plan to look into what is going on, sorry. So closing this issue.
I suggest to find what is causing the unknown error and to fix it.

**Closed by evernat** 2021-11-29 00:08 UTC
