### ISSUE TITLE
spring boot 1.5.3

### ISSUE THREAD

**Issue by wenzhongyi** [javamelody/javamelody#745] opened 2018-05-29 05:30 UTC
Failed to destroy the filter named [javamelody] of type [net.bull.javamelody.MonitoringFilter]
java.lang.NoSuchMethodError: org.apache.log4j.Logger.removeAppender(Lorg/apache/log4j/Appender;)V
	at net.bull.javamelody.Log4JAppender.deregister(Log4JAppender.java:55)

**Comment by evernat** [comment] 2018-05-29 07:12
It is a duplicate of #583 

As said in the SLF4J documentation:
http://www.slf4j.org/legacy.html#log4j-over-slf4j
when adding the log4j-over-slf4j dependency, you need to remove the log4j dependency.

Quote:

> To use log4j-over-slf4j in your own application, the first step is to locate and then to replace log4j.jar with log4j-over-slf4j.jar. 

And you can check that log4j-over-slf4j is not too old.

**Closed by evernat** 2018-05-29 07:12 UTC
