### ISSUE TITLE
SQL statistics not available on Tomcat - rebinding datasource failed, skipping it

### ISSUE THREAD

**Issue by Knooger** [javamelody/javamelody#1130] opened 2022-12-07 12:40 UTC
Hi,
I have discovered that the SQL statistics gathering does not work on the newest versions of Apache Tomcat. 
- Apache Tomcat 8.5.83+
- Apache Tomcat 9.0.67+

I've checked the release notes for those versions but have not noticed anything that could be the culprit.
https://tomcat.apache.org/tomcat-8.5-doc/changelog.html
https://tomcat.apache.org/tomcat-9.0-doc/changelog.html

I'm fine sticking with older Tomcat versions, but I'm posting this as it might save the headache for someone else when debugging why it does not work. If you cannot reproduce this on a simple project I can do some additional testing or provide more information.

Thanks

Adding JavaMelody logs for reference
Works on Apache Tomcat 8.0.0 to 8.5.82
> Wed Dec 07 12:46:47 CET 2022     DEBUG     JavaMelody listener init started
Wed Dec 07 12:46:47 CET 2022     DEBUG     datasources found in JNDI: [java:/comp/env/jdbc/MyDataSource]
Wed Dec 07 12:46:48 CET 2022     DEBUG     datasource rebinded: java:/comp/env/jdbc/MyDataSource from class org.apache.tomcat.dbcp.dbcp2.BasicDataSource to class com.sun.proxy.$Proxy4
Wed Dec 07 12:46:48 CET 2022     DEBUG     JavaMelody listener init done in 129 ms
Wed Dec 07 12:46:50 CET 2022     DEBUG     JavaMelody filter init started
Wed Dec 07 12:46:50 CET 2022     DEBUG     OS: Linux unknown, amd64/64
Wed Dec 07 12:46:50 CET 2022     DEBUG     Java: OpenJDK Runtime Environment, 1.8.0_302-b08
Wed Dec 07 12:46:50 CET 2022     DEBUG     Server: Apache Tomcat/8.5.82
Wed Dec 07 12:46:50 CET 2022     DEBUG     Webapp context: /test
Wed Dec 07 12:46:50 CET 2022     DEBUG     JavaMelody version: 1.91.0
Wed Dec 07 12:46:50 CET 2022     DEBUG     JavaMelody classes loaded from: file:/home/REDACTED/WEB-INF/lib/javamelody-core-1.91.0.jar
Wed Dec 07 12:46:50 CET 2022     DEBUG     Application type: Classic
Wed Dec 07 12:46:50 CET 2022     DEBUG     Application version: 1.0
Wed Dec 07 12:46:50 CET 2022     DEBUG     Host: fedora@192.168.1.49
Wed Dec 07 12:46:50 CET 2022     DEBUG     parameter defined: log=true
Wed Dec 07 12:46:50 CET 2022     DEBUG     parameter defined: datasources=java:/comp/env/jdbc/MyDataSource
Wed Dec 07 12:46:50 CET 2022     DEBUG     log listeners initialized
Wed Dec 07 12:46:50 CET 2022     DEBUG     datasources found in JNDI: [java:/comp/env/jdbc/MyDataSource]
Wed Dec 07 12:46:50 CET 2022     DEBUG     datasource rebinded: java:/comp/env/jdbc/MyDataSource from class org.apache.tomcat.dbcp.dbcp2.BasicDataSource to class com.sun.proxy.$Proxy4
Wed Dec 07 12:46:50 CET 2022     DEBUG     counters initialized
Wed Dec 07 12:46:50 CET 2022     DEBUG     counters data read from files in /tmp/javamelody/fedora
Wed Dec 07 12:46:50 CET 2022     DEBUG     collect task scheduled every 60s
Wed Dec 07 12:46:50 CET 2022     DEBUG     first collect of data done
Wed Dec 07 12:46:50 CET 2022     DEBUG     JavaMelody filter init done in 140 ms

Broken from Apache Tomcat 8.5.83+
> Wed Dec 07 12:41:23 CET 2022     DEBUG     JavaMelody listener init started
Wed Dec 07 12:41:23 CET 2022     DEBUG     datasources found in JNDI: [java:/comp/env/jdbc/MyDataSource]
Wed Dec 07 12:41:23 CET 2022     DEBUG     rebinding datasource java:/comp/env/jdbc/MyDataSource failed, skipping it
Wed Dec 07 12:41:23 CET 2022     DEBUG     JavaMelody listener init done in 171 ms
Wed Dec 07 12:41:26 CET 2022     DEBUG     JavaMelody filter init started
Wed Dec 07 12:41:26 CET 2022     DEBUG     OS: Linux unknown, amd64/64
Wed Dec 07 12:41:26 CET 2022     DEBUG     Java: OpenJDK Runtime Environment, 1.8.0_302-b08
Wed Dec 07 12:41:26 CET 2022     DEBUG     Server: Apache Tomcat/8.5.83
Wed Dec 07 12:41:26 CET 2022     DEBUG     Webapp context: /test
Wed Dec 07 12:41:26 CET 2022     DEBUG     JavaMelody version: 1.91.0
Wed Dec 07 12:41:26 CET 2022     DEBUG     JavaMelody classes loaded from: file:/home/REDACTED/WEB-INF/lib/javamelody-core-1.91.0.jar
Wed Dec 07 12:41:26 CET 2022     DEBUG     Application type: Classic
Wed Dec 07 12:41:26 CET 2022     DEBUG     Application version: 1.0
Wed Dec 07 12:41:26 CET 2022     DEBUG     Host: fedora@192.168.1.49
Wed Dec 07 12:41:26 CET 2022     DEBUG     parameter defined: log=true
Wed Dec 07 12:41:26 CET 2022     DEBUG     parameter defined: datasources=java:/comp/env/jdbc/MyDataSource
Wed Dec 07 12:41:26 CET 2022     DEBUG     log listeners initialized
Wed Dec 07 12:41:26 CET 2022     DEBUG     datasources found in JNDI: [java:/comp/env/jdbc/MyDataSource]
Wed Dec 07 12:41:26 CET 2022     DEBUG     rebinding datasource java:/comp/env/jdbc/MyDataSource failed, skipping it
Wed Dec 07 12:41:26 CET 2022     DEBUG     counters initialized
Wed Dec 07 12:41:26 CET 2022     DEBUG     counters data read from files in /tmp/javamelody/fedora
Wed Dec 07 12:41:26 CET 2022     DEBUG     collect task scheduled every 60s
Wed Dec 07 12:41:26 CET 2022     DEBUG     first collect of data done
Wed Dec 07 12:41:26 CET 2022     DEBUG     JavaMelody filter init done in 207 ms

The same goes for Apache Tomcat 9 - Works fro m9.0.0 to 9.0.65, on 9.0.67+ Broken

**Comment by evernat** [comment] 2023-01-15 16:49
duplicate of #1131 which is fixed now, to be released

**Closed by evernat** 2023-01-15 16:49 UTC
