### ISSUE TITLE
Сompatibility with Spring-session

### ISSUE THREAD

**Issue by gshadrin** [javamelody/javamelody#1138] opened 2023-01-10 08:01 UTC
We use Spring-session. And we use JavaMelody for monitoring sessions.

JavaMelody uses net.bull.javamelody.SessionListener for monitoring sessions. It is implementation of HttpSessionListener from servlet API.

Spring-session have SessionEventHttpSessionListenerAdapter for capability with servlet api session listeners. It listens Spring session events and submit http session events. Wherein it creates ExpiringSessionHttpSession (wrapper for spring session).
```
private HttpSessionEvent createHttpSessionEvent(AbstractSessionEvent event) {
	ExpiringSession session = event.getSession();
	HttpSession httpSession = new ExpiringSessionHttpSession<ExpiringSession>(session,
				this.context);
	HttpSessionEvent httpSessionEvent = new HttpSessionEvent(httpSession);
	return httpSessionEvent;
}
```

We use SessionEventHttpSessionListenerAdapter for working net.bull.javamelody.SessionListener. Spring sessions successful displays in JavaMelody sessions view.

But we have a problem. JavaMelody button "invalidate session" doesn't work correct. JavaMelody uses http session method invalidate for handling this button. The implementation method in ExpiringSessionHttpSession (part of Spring) looks like dummy:
```
public void invalidate() {
	checkState();
	this.invalidated = true;
}
```
In facts, it only set invalidate = true in adapter, but it is not invalidate session in Spring session registry. Real spring session continues be valid, and user can be used this session.

Could you have solution for this problem?

I found some solution but I don't think that it's good. We can override spring SessionEventHttpSessionListenerAdapter and ExpiringSessionHttpSession. And we can override method invalidate (adding call session registry). In this case, JavaMelody will invalidate session in registry. 

But this solution need customization for Spring classes. Do you have solution inside JavaMelody for this problem? Or JavaMelody doesn't compatibility with SpringSession?

**Comment by evernat** [comment] 2023-02-02 23:52
spring-session and javamelody had some cases of incompatibility in the past quite long ago, if you look javamelody issues 826, 906 and 911. Or in my opinion, spring-session had some cases of incompatibility in the past with the java servlet api and so with all JavaEE servers (using javamelody or not), if you look at the causes of the issues above for example.

For your case, if you say that SessionEventHttpSessionListenerAdapter of spring-session replaces the HttpSession of the user with another one where invalidate() does nothing, then I would answer that it is not a javamelody issue if spring-session chooses to ignore what is written for invalidate() in the servlet api. Given that it is not an issue caused by javamelody and that javamelody uses a simple method of the servlet api, this issue will be closed as invalid.

And then you could do:
- ask spring-session to implement HttpSession methods as specified by the servlet api, if spring-session is able to,
- or override and fix the spring-session SessionEventHttpSessionListenerAdapter by yourself,
- or do without spring-session with this configuration,
- or do not use the invalidate session button in javamelody when you use spring-session and live with it,
- or anything similar.

**Closed by evernat** 2023-02-02 23:52 UTC
