### ISSUE TITLE
Thread contention in JdbcWrapperHelper

### ISSUE THREAD

**Issue by jiri-pejchal** [javamelody/javamelody#963] opened 2020-11-23 21:36 UTC
There is a thread contention in JdbcWrapperHelper:

![image](https://user-images.githubusercontent.com/1450087/100018008-0aab8500-2ddc-11eb-9a9d-73c08d26672e.png)

```java
private static final Map<Class<?>, Constructor<?>> PROXY_CACHE = Collections
			.synchronizedMap(new WeakHashMap<Class<?>, Constructor<?>>());
```
Perhaps some sort of `ConcurrentReferenceHashMap` could be use?

Tested on jdk 15.

**Comment by evernat** [comment] 2020-11-24 12:32
You said:
> Tested on jdk 15

How do you test that? That is, how many connections/statements per second on how many threads? Or better do you have something like some test code to reproduce the issue?
Which version of jdk 15 exactly?
Since biased locking has been disabled in jdk 15, can you test with -XX:+BiasedLocking on the command line to see if it makes any difference for you?

**Comment by evernat** [comment] 2020-12-09 23:16
Any news?

**Comment by jiri-pejchal** [comment] 2020-12-10 21:21
The measurement took place on a production tomcat during peak traffic - 140k SQL hits per minute according to javamelody.
```
$ java --version
openjdk 15.0.1 2020-10-20
OpenJDK Runtime Environment AdoptOpenJDK (build 15.0.1+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 15.0.1+9, mixed mode, sharing)
```
I have not been able to reproduce it again.

**Comment by evernat** [comment] 2021-05-08 22:51
Thank you for the info.
140k hits per minute is a lot indeed for a single JVM.

Perhaps there was something else which was causing "slowness", related to this JDK 15 which was just 1 month old in Nov 2020 and which had just disabled biased locking on threads or related to this peak traffic and perhaps outside the JVM. This undefined "slowness" may be the root cause and the contention at that moment may have been one of the visible consequences.
Once this undefined "slowness" was removed, that consequence was not reproduceable anymore.
Anyway, what is sure is that the probably extreme conditions or the specific conditions with openjdk 15.0.1 to produce the issue can't be reproduced at the moment.

The issue is not reproduceable, so I close this issue for the moment.

**Closed by evernat** 2021-05-08 22:51 UTC
