### ISSUE TITLE
Javamelody Dependency Tree not working since version 1.65.1

### ISSUE THREAD

**Issue by jkrishnaraj** [javamelody/javamelody#718] opened 2018-01-09 13:55 UTC
See issue #717 for details
Dependency link in javamelody is not working. After lengthy research now I can reproduce the issue on will. The issue is with these 2 jar files in the application  WEB-INF/lib
axiom-dom-1.2.10.jar
axiom-impl-1.2.10.jar
Once I remove them the WEB-INF/lib is works. How do we resolve this ? I cannot remove those 2 jar files permanent.

**Comment by evernat** [comment] 2018-01-10 14:34
Thanks for finding the examples files causing the issue. It was a NPE caused by a particular case in pom.xml of the jar files.
It is fixed now by c9d0dc2 and ready for the next release (1.71).
You can download a snapshot build of the javamelody-core jar for the monitored webapp in a few minutes:
https://javamelody.ci.cloudbees.com/job/javamelody/net.bull.javamelody$javamelody-core/

**Closed by evernat** 2018-01-10 14:34 UTC
