### ISSUE TITLE
Monitoring multiple persistence units

### ISSUE THREAD

**Issue by nalmeida84** [javamelody/javamelody#853] opened 2019-08-20 11:56 UTC
First PU it's working right but the second fail. I saw that when the javax.persistence.Persistence.createEntityManagerFactory method try to create the provider, a JavaMelody and Hibernate are listed. For my monitored persistence unit, PU1, it's the expected behavior but in the second persistence unit, PU2, the provider used is the provided by JavaMelody too... The persistence factory it's not choosing the right one because JavaMelody's provider it's telling that it's a "org.hibernate.jpa.HibernatePersistenceProvider".

<property name="net.bull.javamelody.jpa.provider" value="org.hibernate.jpa.HibernatePersistenceProvider" />

The big problem to me is that the JavaMelody provider is given but the database url itsn't prepared to be monitored, so the second, and not monitored, connection isn't opened because not "driver" param in the given jdbc url.

Also, if I try to monitor the second persistence unit with JavaMelody I only can see one connection (the last configured). It's not possible to monitoring multiple database connections, itsn't?

```
<?xml version="1.0" encoding="UTF-8"?>
<persistence version="1.0"
	xmlns="http://java.sun.com/xml/ns/persistence" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://java.sun.com/xml/ns/persistence http://java.sun.com/xml/ns/persistence/persistence_1_0.xsd">
	<persistence-unit name="PU1" transaction-type="RESOURCE_LOCAL">
		<provider>net.bull.javamelody.JpaPersistence</provider>
		<class>xxxx</class>
		<exclude-unlisted-classes>true</exclude-unlisted-classes> 
		<properties>
			<property name="net.bull.javamelody.jpa.provider" value="org.hibernate.jpa.HibernatePersistenceProvider" />
			<property name="hibernate.connection.driver_class" value="net.bull.javamelody.JdbcDriver" />
			<property name="hibernate.connection.url" value="jdbc:postgresql://xxx-postgres:5432/xxx?driver=org.postgresql.Driver" />
		</properties>
	</persistence-unit>
    <persistence-unit name="PU2" transaction-type="RESOURCE_LOCAL">
        <provider>org.hibernate.jpa.HibernatePersistenceProvider</provider>
		<class>xxxx</class>
        <exclude-unlisted-classes>true</exclude-unlisted-classes> 
        <properties>
            <property name="hibernate.connection.driver_class" value="org.postgresql.Driver" />
            <property name="hibernate.connection.url" value="jdbc:postgresql://zzz:5432/zzz" />
        </properties>
    </persistence-unit>
</persistence>
```

**Comment by nalmeida84** [comment] 2019-08-20 14:11
Maybe a possible solution is to check in the JpaPersistence class for the JavaMelody driver in the entity manager and return null if not. This is going to force to check next provider and jump the JPA JavaMelody wrapping on non monitored connections.

		```
try {
			final EntityManagerFactory entityManagerFactory = persistenceProvider
					.createEntityManagerFactory(unit, map);
			if (entityManagerFactory == null) {
				return null;
			} else {
// TODO: check here for the javamelody driver string and return null if found
}
			return JpaWrapper.createEntityManagerFactoryProxy(entityManagerFactory);
		} finally {
			Thread.currentThread().setContextClassLoader(tccl);
		}
```

**Comment by evernat** [comment] 2019-08-22 16:33
> // TODO: check here for the javamelody driver string and return null if found

We can't do that, because in general there is no javamelody driver used to monitor jdbc connections (in general, jdbc connections are monitored because they are coming from a datasource in JNDI).
By the way, given your configuration without using a datasource and neither a third party connection pool, then Hibernate is using its rudimentary default connection pool which is not intended for use in a production system. That's not recommended.

Then, JavaMelody can monitor jdbc connections from multiple databases. But first, what is your main goal to go step by step? Do you want first to monitor sql requests from all jdbc connections or do you want to monitor JPA/Hibernate requests? They are different things and JavaMelody can do both.
If what you want is to monitor sql requests from jdbc connections, then do not use `net.bull.javamelody.JpaPersistence` and use `net.bull.javamelody.JdbcDriver` (or better, use `hibernate.connection.datasource` and a datasource named like "jdbc/Mydatasource" in JNDI instead of `hibernate.connection.url` and `hibernate.connection.driver_class`).

Then I don't understand what you mean when you try to monitor JPA/hibernate with both persistence units. Can you give the source of a simple project to reproduce the issue?

**Comment by nalmeida84** [comment] 2019-08-23 08:07
Hi,

I'm using a C3P0 pooled connection over Hibernate (5.0.x, JPA 2.1). Anyway, I needed to turn off (set to 0) the `hibernate.c3p0.max_statements` param because was failing due to JavaMelody. I need to degub to try to find the cause.

My application uses a connection for itself and a second connection to another database (different machine) to save some log messages.

To reproduce the issue just set two persistence units, each one pointing to different connections. 

```
<persistence-unit name="PU1" transaction-type="RESOURCE_LOCAL">
		<provider>net.bull.javamelody.JpaPersistence</provider>
<persistence-unit name="PU2" transaction-type="RESOURCE_LOCAL">
        <provider>org.hibernate.jpa.HibernatePersistenceProvider</provider>

```
In my case I don't need to monitor the second connection at all but should be great. 
Now, only way to get the whole set working is to put the JavaMelody provider on both connections and JavaMelody monitors only the last connection setted in the persistence.xml file. If I don't set it on both the non Javamelody provider don't connect.

**Comment by evernat** [comment] 2019-08-25 14:31
Sorry but I don't quite understand "the non Javamelody provider don't connect" and I don't reproduce either.
Since you are not writing a riddle, can you give the source of a simple project to reproduce the issue?
Thanks.

**Comment by nalmeida84** [comment] 2019-08-26 08:21
I can't share actual project but it's not a riddle, it's not common but not complex.

We have one database connection and we want to monitor it. This database connection have they persistence unit with the JavaMelody driver and provider to monitor JPA.

Second connection is for store some log data, it's made to a different machine/database. We don't need to monitor it, but should be a plus. This database have another persistence unit and don't have any config related to JavaMelody.

Both connection are using a C3P0 pool.

Debuggin I saw that the second connection it's never made If I set JavaMelody in out project. When JavaMelody tries to set the provider Hibernate pass two, first is the own JavaMelody provider and second the Hibernate ones. JavaMelody code are always accepting the first one, so it's valid for our first connection but not for the second. I fixed this "jumping" the JPA provider if in the connection URL don't appear the "driver" param. 

Fixing it I have problems with the driver. I'm not sure but I think that JavaMelody only accept one connection for application.

If I have time I'll setup an example but I think that it's not hard to see the whole set and the problem explained. Two connection in one app, each one to databases in different machines with different persistence units using C3P0. First connection is done, second is never made.

Thanks you.

**Comment by evernat** [comment] 2019-12-08 00:30
I have read again this issue. And first, let met say again: javamelody can do JPA monitoring and it can do jdbc (SQL) monitoring, when configured. But JPA monitoring and jdbc (SQL) monitoring have nothing related to each other, so configuration of JPA monitoring has no impact on the jdbc (SQL) monitoring.

> For my monitored persistence unit, PU1, it's the expected behavior but in the second persistence unit, PU2, the provider used is the provided by JavaMelody too

That's the expected behavior of javamelody. (javamelody JpaPersistence is the provider, even without adding `<provider>net.bull.javamelody.JpaPersistence</provider>` and even more so when 1.81.0 will be released.)

Then if you want to monitor sql requests of PU2, configure the jdbc connections like you have done for PU1 (or better, use a jdbc datasource):
```xml
			<property name="hibernate.connection.driver_class" value="net.bull.javamelody.JdbcDriver" />
			<property name="hibernate.connection.url" value="jdbc:postgresql://zzz:5432/zzz?driver=org.postgresql.Driver" />
```

And second, given that it's not clear here, what are the issues for you or what may be expected behavior for us, and given that there is no source to reproduce anything, closing this issue.

**Closed by evernat** 2019-12-08 00:30 UTC
