### ISSUE TITLE
Collector Server: when adding a clustered application, link and chart for http sessions is missing

### ISSUE THREAD

**Issue by dmouch** [javamelody/javamelody#515] opened 2015-11-25 15:14 UTC
Hi, we're migrating to javamelody 1.57.0 and I see an issue still persisting from version 1.28 (which we're still using on most servers).

In the collector server, when adding an application which runs on 1 jboss we're getting the Http Sessions graph and a link next to View Memory Histograms for "View Http Sessions" and "Invalidate Http Sessions" (in System Information area). I have added such servers like:
Add
Name: mytest Url: http://myhost/myapp/

When adding an application that runs on 2 jboss's in a cluster we're not seeing the Http Sessions Graph, nor the links described above. However it seems that viewing current sessions is available if I edit the url on my browser and add &part=sessions
Add
Name: myclustertest Url: http://myhost1/myapp,http://myhost2/myapp

So I'm guessing this is a minor bug? In the case of me changing the url, is the information accurate (sessions from both nodes of the cluster) or do they come from only one of the nodes?

Thank you

**Comment by evernat** [comment] 2015-11-27 23:53
Perahps, you have added the MonitoringFilter in the WEB-INF/web.xml file of the monitored webapp, and you have not added the SessionListener. If yes, add it like:
https://github.com/javamelody/javamelody/wiki/UserGuide#2-webxml-file

**Comment by dmouch** [comment] 2015-11-30 17:38
Actually it is enabled, this is from our web.xml:
   <filter>
       <filter-name>melody-monitoring</filter-name>
       <filter-class>net.bull.javamelody.MonitoringFilter</filter-class>
       <init-param>
           <param-name>system-actions-enabled</param-name>
           <param-value>true</param-value>
       </init-param>
       <init-param>
           <param-name>monitoring-path</param-name>
           <param-value>/app-monitoring</param-value>
       </init-param>
       <init-param>
           <param-name>url-exclude-pattern</param-name>
           <param-value>.*/css/.*|.*/scripts/.*|.*/images/.*</param-value>
       </init-param>
       <init-param>
           <param-name>storage-directory</param-name>
           <param-value>user.home/javamelody/app</param-value>
       </init-param> 
   </filter>
...
   <filter-mapping>
       <filter-name>melody-monitoring</filter-name>
       <url-pattern>/*</url-pattern>
   </filter-mapping> 
....
  <listener>
    <listener-class>net.bull.javamelody.SessionListener</listener-class>
</listener>

The above is from javamelody.jar 1.56 and collector server 1.57

I also have another app running on 1.28.0 (configured a few years back) and collector server 1.28.0 which shows the sessions graphs (and from what it looks like they are wrong, since no session can be seen) but the link is missing. If I add the part=session in the url I can see active sessions. The only additional configuration I can see in web.xml is this:
       <init-param>
           <param-name>datasources</param-name>
           <param-value>jdbc/appDS</param-value>
       </init-param>
       <init-param>
           <param-name>log</param-name>
           <param-value>true</param-value>
       </init-param>

If it helps, both of these  apps are running on jboss 5.0.1, jdk7 on linux.

**Comment by evernat** [comment] 2015-12-22 18:07
It seems that, for some reason, session counts is wonky in your case (jboss 5.0.1 in cluster for one app), between sessionCreated events and sessionDestroyed events. It may be caused by some issue with jboss 5 session replication in cluster.

If you want to fix this in your app, you can create a class in your app (note the PluginMonitoringFilter):
```java
public class YourMonitoringFilter extends net.bull.javamelody.PluginMonitoringFilter {
}
```
and use that class in your web.xml, and also remove SessionListener from web.xml.
For example with config as above:
```xml
   <filter>
       <filter-name>melody-monitoring</filter-name>
       <filter-class>yourpackage.YourMonitoringFilter</filter-class>
       <init-param>
           <param-name>system-actions-enabled</param-name>
           <param-value>true</param-value>
       </init-param>
       <init-param>
           <param-name>monitoring-path</param-name>
           <param-value>/app-monitoring</param-value>
       </init-param>
       <init-param>
           <param-name>url-exclude-pattern</param-name>
           <param-value>.*/css/.*|.*/scripts/.*|.*/images/.*</param-value>
       </init-param>
       <init-param>
           <param-name>storage-directory</param-name>
           <param-value>user.home/javamelody/app</param-value>
       </init-param> 
   </filter>
...
   <filter-mapping>
       <filter-name>melody-monitoring</filter-name>
       <url-pattern>/*</url-pattern>
   </filter-mapping> 
<!-- No SessionListener -->
```

And I think that I will not look at this issue as a valid javamelody bug, because:
- you are the only one speaking about it which is suspect if it was a javamelody bug,
- and jboss 5 is very very old and unsupported by Red Hat (perhaps with many jboss bugs as much as we know: supporting jboss 5 is not a priority for javamelody).

So closing as invalid, sorry. But you have a workaround above.

**Closed by evernat** 2015-12-22 18:07 UTC
