### ISSUE TITLE
Missing support for IBM Liberty Profile

### ISSUE THREAD

**Issue by GoogleCodeExporter** [javamelody/javamelody#411] opened 2015-06-21 16:38 UTC
```
What steps will reproduce the problem?
1. Run JavaMelody 1.50.0 on IBM Liberty Profile <=8.5.5.2

What is the expected output? What do you see instead?
-We expect JDBC-monitoring, but JavaMelody does not pick up the JNDI/data 
source of the Liberty Profile container.
-We expect less exceptions because of already closed stream when call to 
flushBuffer().

What version of the product are you using? On what application server, JDK,
operating system?
JavaMelody 1.50.0, IBM Liberty Profile 8.5.5.2, IBM JDK 7_21 (same version of 
oracle aswell)


Please provide any additional information below.
We have edited the source files of JavaMelody 1.50.0 with the changes in the 
attachment. Only a few methods edited so easy to diff with original source.

We hope this is enough information for the issue to be accepted.

Sincerely
John


```

Original issue reported on code.google.com by `jahes...@gmail.com` on 27 May 2014 at 12:22

Attachments:
- [FilterServletResponseWrapper.java](https://storage.googleapis.com/google-code-attachments/javamelody/issue-411/comment-0/FilterServletResponseWrapper.java)
- [HtmlJavaInformationsReport.java](https://storage.googleapis.com/google-code-attachments/javamelody/issue-411/comment-0/HtmlJavaInformationsReport.java)
- [JdbcWrapper.java](https://storage.googleapis.com/google-code-attachments/javamelody/issue-411/comment-0/JdbcWrapper.java)

**Comment by hestad** [comment] 2015-12-16 09:17
We still have problems with flushbuffers / closed streams @ Liberty Profile 8.5.5.7 / IBM JDK 7 and 8. The container has gained popularity and I wondered if we could raise the priority of this issue?

**Comment by evernat** [comment] 2015-12-16 09:22
Again, given that:
- the exceptions on closed stream is an IBM liberty profile issue, which should be fixed by IBM (we don't want to swallow exceptions just because of them), and merging the JDBC monitoring changes from the patch is useless if IBM does not fix exceptions first,
- the server info is also an IBM liberty profile issue,
- and there are TODO comments in the patch, unanswered at the moment, then the patch can't be merged for now.
the priority of the issue is "low".

**Comment by hestad** [comment] 2015-12-20 21:51
I've looked a bit further into this issue. I've read through this old discussion: https://groups.google.com/forum/#!topic/javamelody/kX31sRTFrHE/discussion

A datasource-change should be OK to add even if we still use a little patch for the flushes. Although I agree that the current patch has its weak points. We will create a better suited PR, something similar to the Wildfly addition in 1.58.

I agree that I should report CXFs flushBuffer() -> close() routine, it looks a bit off. Further, reading this: http://grepcode.com/file/repository.grepcode.com/java/root/jdk/openjdk/8u40-b25/java/io/Flushable.java/ gives no real guideline on when to give IOException if the stream is already closed (the Closable/AutoClosable interface has way better doc and states that close() should be idempotent). Do you have any better documentation on this other than "all the other containers check if a stream is closed before flushing?" If not it feels a bit "wrong" to submit as a bug to IBM wasdev.

Based on the stack-trace in the aforementioned discussion, I'm boggled by JavaMelody's flushBuffer -> flush shortcut. If we exclude JavaMelody, Cxf would call IBM Liberty Profiles SRTServletResonse class flushBuffer() (which actually check if its already flushed and/or if the stream/writer is closed), meanwhile including JavaMelody it drops the call to the wrapped HttpServletResponse.flushBuffer() and rather call flush() directly on OutputStream/Writer. Why is that?

Found this @ vaadin.com: https://dev.vaadin.com/ticket/12283 and check out the second change https://dev.vaadin.com/changeset/049b9d99ff887e9408e23cbd169431140dd0afa9/vaadin (not that it is directly related, but it is interesting to see similar "stream is closed"-problems.

**Comment by evernat** [comment] 2015-12-20 23:35
The CXF issue about CXFs flushBuffer() -> close() routine: https://issues.apache.org/jira/browse/CXF-6720

**Comment by hestad** [comment] 2015-12-21 13:51
Nice oberservation! And here is the issue I created @ WasDev: https://developer.ibm.com/answers/questions/244982/why-does-httpoutputstreamflush-when-stream-is-clos.html

**Comment by GisleGrimen** [comment] 2016-02-12 09:14
This issue is partly fixed by the changes they made in Apache CXF in version 3.1.5, 3.0.8, 3.2.0.

As is, the solution works and responses are returned to the client, but JavaMelody will still record that the request failed. This is due to the fact that JavaMelody still calls flush on a stream that is already closed, which in case of WebSphere Liberty result in an Exception being thrown.

I have looked into the code and found a simple way to hack away the issue completely. 

By adding a filter in front of Apache CXF that starts AsyncContext the problem is solved as JavaMelody does not call flush if request is marked as Async. The filter will then only start an async context and on return complete the request. All processing is still being done synchronously.

A simple filter with following code would then make it possible to run correctly JavaMelody Apache CXF and WebSphere Liberty. 

 @Override
    public void doFilter(ServletRequest request, ServletResponse response, FilterChain chain) throws IOException, ServletException {

        AsyncContext context = null;
        try {

            if(request instanceof HttpServletRequest){
                context = ((HttpServletRequest)request).startAsync();
            }
            chain.doFilter(request, response);
        }finally{
            context.complete();
        }
    }

**Comment by evernat** [comment] 2016-02-21 20:37
@GisleGrimen 
For the flush on a already closed output stream, there is a change for issue #532 which probably helps here ([d8f114a](https://github.com/javamelody/javamelody/commit/d8f114a4dbda659a9e34bfd2f24a3adc13a9e260)).
There is a nightly build available at:
https://javamelody.ci.cloudbees.com/job/javamelody/ws/javamelody-core/javamelody.jar

**Comment by evernat** [comment] 2017-11-23 00:15
This issue is probably obsolete now, because Liberty Profile has changed, CXF has changed, javamelody has changed. So closing the issue as such.

For reference, the main change for adding jdbc monitoring was in the JdbcWrapper#rewrapDataSource method (see [initial patch](https://github.com/javamelody/javamelody/files/1497768/issue411_v0.1.txt)):
```java
		} else if (websphereLibertyProfile
				&& connection.getClass().getName().contains("WSJdbcConnection")) {
			final String conFieldName = "connImpl";
			Connection con = (Connection) JdbcWrapperHelper.getFieldValue(connection, conFieldName);
			// on teste isProxyAlready ici pour raison de perf
			if (!isProxyAlready(con)) {
				con = createConnectionProxy(con);
				JdbcWrapperHelper.setFieldValue(connection, conFieldName, con);
			}
 		}
```

**Closed by evernat** 2017-11-23 00:15 UTC
Labels: auto-migrated, enhancement, Priority-Low
