### ISSUE TITLE
Not able to log out of the Javamelody UI.

### ISSUE THREAD

**Issue by ajayyadav92** [javamelody/javamelody#1150] opened 2023-03-16 16:09 UTC
Greetings to all.

I can log in Javamelody UI, but I am unable to logout it. As soon as you click the logout button, the javamelody dashboard page reappears. unable to successfully log out.

Note: If I delete my browser's cache, I can totally log out.

Please explain how to close the Javamelody user interface.
(Using: Java, Spring, Tomcat 9, **javamelody-core-1.72.0.jar**)

**Comment by evernat** [comment] 2023-03-19 17:01
Nothing in javamelody prevents you from accessing the monitoring page of javamelody, except authentication if you have configured it somehow.

There is a logout item in the menu of the monitoring page, if the browser has a valid http session. When clicked, the logout item invalidates this http session. Then it redirects to the monitoring page. The name "logout" may be misleading in your case, but it means just that : "invalidate my http session" and in many webapp, the webapp forbids access to the pages of the webapp including the monitoring page.

What your webapp does when an url like the monitoring page is accessed without a http session is up to you, not to javamelody. For example, you may have a servlet filter to redirect to a login page in your webapp when the browser does not have a valid http session.

If your webapp does nothing special when there is no http session, the monitoring page is displayed when asked to (the monitoring page does not need and does not create a http session by the way). If you have configured basic auth with the authorized-users javamelody parameter, this basic auth is not related to http session, so the basic auth is still valid if you have a http session or if you don't have a http session, for example after clicking the logout item which is misleading in this case.

So the issue is invalid, probably because you misunderstood what the logout item does. Closing the issue as such.

> Note: If I delete my browser's cache, I can totally log out.
I don't know what is the cause of that, but I don't know what is your browser or if you have configured authorized-users or some other authentication.

**Closed by evernat** 2023-03-19 17:01 UTC
