### ISSUE TITLE
Monitoring path param is ignored after upgrade to JDK8

### ISSUE THREAD

**Issue by peterjurkovic** [javamelody/javamelody#498] opened 2015-09-21 10:32 UTC
After upgrade from Java7 to `1.8.0_60-b27` JavaMelody's `monitoring-path` param defined in `web.xml` is being ignored. 

The monitoring section was defined to path `www.domain.com/xxx/monitoring` but after Java upgrade is in the default location `www.domain.com/monitoring`.

my `web.xml` conf: 

    <filter>
    	<filter-name>javamelody</filter-name>
    	<filter-class>net.bull.javamelody.MonitoringFilter</filter-class>
    	<async-supported>true</async-supported>
    	<init-param>
    		<param-name>monitoring-path</param-name>
    		<param-value>/xxx/monitoring</param-value>
    	</init-param>
    	<init-param>
    		<param-name>url-exclude-pattern</param-name>
    		<param-value>/resources/.*</param-value>
    	</init-param>
    
    </filter>
    <filter-mapping>
    	<filter-name>javamelody</filter-name>
    	<url-pattern>/*</url-pattern>
    	<dispatcher>REQUEST</dispatcher>
    	<dispatcher>ASYNC</dispatcher>
    </filter-mapping>
    <listener>
    	<listener-class>net.bull.javamelody.SessionListener</listener-class>
    </listener>

Used technologies:
*JavaMelody 1.57.0, Apache Tomcat 7, Spring*

Thank you for help.

**Comment by evernat** [comment] 2015-09-22 13:47
I do not reproduce the issue.
Do you have the source of a simple project (using Maven if possible) to reproduce it?

**Comment by peterjurkovic** [comment] 2015-09-22 17:14
I have already found out the issue. It's cause by `filter-name` value. In case the filter name is `monitoring` it does not work, otherwise e.g. the name is `javamelody` it works.

**Comment by evernat** [comment] 2015-09-22 18:59
OK. In that case, the description above is a bit wrong.
And in fact, this issue is a duplicate of issue #459

**Closed by evernat** 2015-09-22 18:59 UTC
