### ISSUE TITLE
Error using 1.68.0; Downgrade to 1.67.0 fixes the issue

### ISSUE THREAD

**Issue by hth** [javamelody/javamelody#646] opened 2017-07-09 04:44 UTC
net.bull.javamelody.JobGlobalListener.initJobGlobalListener(JobGlobalListener.java:48)

**Comment by evernat** [comment] 2017-07-09 14:15
Do you use Quartz version 2 ?
If yes, there is an issue #645 which is fixed in master.
If you use the javamelody-core in your webapp, you can download a new build at:
https://javamelody.ci.cloudbees.com/job/javamelody/net.bull.javamelody$javamelody-core/

**Comment by hth** [comment] 2017-07-09 16:38
Yes I do have Quartz Version 2. If that fixes the issue please feel free to close this. I would recommend to keep it open until next version is released.

**Comment by evernat** [comment] 2017-07-09 17:05
closed as duplicate of #645
The release notes for the next release mentions the issue.
Thanks anyway.

**Closed by evernat** 2017-07-09 17:05 UTC
