### ISSUE TITLE
Empty cache entry lists for ehcache3 caches

### ISSUE THREAD

**Issue by stolp** [javamelody/javamelody#834] opened 2019-05-07 22:37 UTC
While testing a SNAPSHOT of javamelody 1.78 regarding changes in #574 I noticed that while the ehcache3 caches are present in the 'Data caches' sections clicking on their links yields a completly empty page.

Sadly, there are no stack traces present in the  sever log.

**Comment by evernat** [comment] 2019-05-19 23:38
If there is no stack trace in the standard or error output of the server, can you debug step by step with a breakpoint in net.bull.javamelody.HtmlJCacheInformationsReport in order to find the exception?
Thank you.

**Comment by stolp** [comment] 2019-05-21 19:39
Yes, though this might take a few days. I am currently on vacation.

**Comment by stolp** [comment] 2019-05-26 19:42
I checked this now. No exceptions are raised during the display of the individual cache sections. Likewise the individual 'Clear Cache' buttons as well as the 'Clear All Caches' yield no changes in the listed cache entries.

There is something special in our setup which may be interest here:

We have two CacheManager objects active in our application, one for hibernate second level caching and one for application level caching. All five caches contained therein are listed properly in the 'Data Caches' section of JavaMelody and do contain sensible information.

Not sure if this is helpful or relevant.

Please let me know if I can add more information.

**Comment by gtricot** [comment] 2019-07-17 13:01
Hi ! 
I got the same blank page when displaying JCache cache content details with URI part=jcacheKeys&cacheId=XXX.
No stack in the logs.

I put a breakpoint in JCacheInformations class :

	public static JCacheInformations buildJCacheInformationsWithKeys(String cacheId) {
		assert JCACHE_AVAILABLE;
		assert cacheId != null;
		for (final CachingProvider cachingProvider : Caching.getCachingProviders()) {
			final CacheManager cacheManager = cachingProvider.getCacheManager();
			for (final String cacheName : cacheManager.getCacheNames()) {
				if (cacheName.equals(cacheId)) {
					// getCache may never return null
					final Cache<Object, Object> cache = cacheManager.getCache(cacheId);
					final List<Object> cacheKeys = new ArrayList<Object>();
					for (final Entry<Object, Object> entry : cache) {
						cacheKeys.add(entry.getKey());
					}
					for (final JCacheInformations cacheInformations : buildJCacheInformationsList()) {
						if (cacheInformations.getName().equals(cacheId)) {
							cacheInformations.cacheKeys = cacheKeys;
							return cacheInformations; // NOPMD
						}
					}
				}
			}
		}
		return null;
	}

The problem is that cacheManager.getCacheNames() returned an empty list (cacheManager being an instance of Eh107CacheManager).
Any idea about why cacheManager doesn't return cache names...

Hope this can help...

**Comment by evernat** [comment] 2019-07-17 21:37
It seems that the cache to be displayed exists in MBeans but is not found in JSR107 caching providers.
I suppose that there is not something special in the encoding of the cacheId (the XXX in part=jcacheKeys&cacheId=XXX of the URL).
And I think that in both your cases here, for every provider in javax.cache.Caching.getCachingProviders(), cachingProvider.getCacheManager().getCachesNames() always returns an empty list.
It seems to happen for some configuration(s) of caches or if several webapps are deployed in the same server.
If cachingProvider.getCacheManager().getCachesNames() returns an empty list and probably cachingProvider.getCacheManager().getCache(cacheId) returns a null value, javamelody has no way to display the cache keys (and size of the cache) as it is supposed to in this page.

So I will probably add an error message instead of a blank page in this case.

**Comment by stolp** [comment] 2019-07-17 22:44
Thanks a lot for the analysis. I checked this and can confirm that cachingProvider.getCacheManager().getCachesNames()  does *not* return an empty list.

BUT ...

These caches are lazily constructed when the first HTTP session is created. Could it be the case that JavaMelody is not picking those up at that point of time?

Please let me know if I can add some more testing.

**Comment by evernat** [comment] 2019-07-17 23:08
@stolp 
Yes, you can do the test in javamelody after lazily constructing your caches.
But I suppose that if the cache(s) having the issue exist in MBeans tree and are displayed in javamelody then they were already lazily constructed and still have the issue. So the cache(s) having the issue are still not found and the conclusion is still the same as before.
Can you confirm that cachingProvider.getCacheManager().getCachesNames() does not contain the cacheId to be found?
Can you confirm that there is nothing special with cacheId in the URL (such as `%` or `\` or empty) ?

**Comment by stolp** [comment] 2019-07-18 08:47
@evernat 
All caches are correctly listed in the MBeans section and in the Data Caches section of Javamelody.
Listing cachingProvider.getCacheManager().getCachesNames() in the application also shows all corresponding entries.

The cache ids contain fully qualified class names (including dots) or standard Hibernate cache names (including hyphens) like below:
/monitoring?part=jcacheKeys&cacheId=default-query-results-region

I can debug this further, please let me know where to look.

**Comment by evernat** [comment] 2019-07-21 13:57
@stolp 
If you can debug with a breakpoint, it would help to know why the following method returns null instead of return an object with cache keys. It's buildJCacheInformationsWithKeys in the class net.bull.javamelody.internal.model.JCacheInformations.

```java
	public static JCacheInformations buildJCacheInformationsWithKeys(String cacheId) {
		assert JCACHE_AVAILABLE;
		assert cacheId != null;
		for (final CachingProvider cachingProvider : Caching.getCachingProviders()) {
			final CacheManager cacheManager = cachingProvider.getCacheManager();
			for (final String cacheName : cacheManager.getCacheNames()) {
				if (cacheName.equals(cacheId)) {
					// getCache may never return null
					final Cache<Object, Object> cache = cacheManager.getCache(cacheId);
					final List<Object> cacheKeys = new ArrayList<Object>();
					for (final Entry<Object, Object> entry : cache) {
						cacheKeys.add(entry.getKey());
					}
					for (final JCacheInformations cacheInformations : buildJCacheInformationsList()) {
						if (cacheInformations.getName().equals(cacheId)) {
							cacheInformations.cacheKeys = cacheKeys;
							return cacheInformations; // NOPMD
						}
					}
				}
			}
		}
		return null;
	}
```

You said that getCacheNames() contains all entries. So is it equals(cacheId) which does not match or getCache(cacheId) which does not work or you have several caches with the same name perhaps?

**Comment by stolp** [comment] 2019-07-21 15:42
@evernat

I debugged this to the point that cacheManager.getCacheNames() is always returning an empty list of cache names. This also applies to buildJCacheInformationsList() in the same class but due to the results of the call to getJsr107CacheStatistics() a valid list of caches is found there nonetheless.

This might sound a contradiction to my previous statement that cachingProvider.getCacheManager().getCachesNames() is returning a list of caches.

The difference I can spot here is that in my case the cache manager is resolving with an explicit ClassLoader
 argument:

```
final CacheManager cacheManager = cachingProvider.getCacheManager(uri, Thread.currentThread()
                .getContextClassLoader());
```
while javamelody is using the default class loader:

`final CacheManager cacheManager  = cachingProvider.getCacheManager()`

As mentioned initially one of the cache manager instances is initialized and controlled by Hibernate 5. I am yet unsure if Hibernate is using the same style but I strongly suspect it is using a similar way.

Hope this helps. Please let me know if I can help out further with this.

**Comment by evernat** [comment] 2019-07-21 22:04
@stolp 
I don't think that the classloader is an issue. Ehcache JCache and Hibernate JCache also use the same default classloader. Your example would certainly work the same way if you use `CachingProvider.getDefaultClassLoader`.

But it could be the uri. Have you configured a property `hibernate.javax.cache.uri` in Hibernate ?
If yes, for which reason have you done that and does it workaround the issue if you remove that property?
According to ehcache mbeans, there is a mbean "key property" named "CacheManager" which could be read to find all possible URIs (paths of configuration files).

**Comment by gtricot** [comment] 2019-07-22 09:56
@evernat 
After further debugging, I saw that there were 2 CacheManagers (Eh107CacheManager instances) registered in the CachingProvider (EhcacheCachingProvider instance) :
- A "default" one, registered under URI : "urn:X-ehcache:jsr107-default-config"
- Spring Boot's configured one under URI configured in application.properties (spring.cache.jcache.config=classpath:conf/jcache.xml with my configuration)

The problem is that cachingProvider.getCacheManager() without parameter returns default cacheManager.
Replacing this call by : cachingProvider.getCacheManager(new URI("classpath:conf/jcache.xml"), null) returns the one that contains all my cache definitions.

Finally, I can't see any entry in cache detail's page : cacheManager.getCache(cacheId) returns an Eh107Cache instance but the loop over cache entries is never executed...

**Comment by stolp** [comment] 2019-07-22 13:46
@evernat

> Have you configured a property hibernate.javax.cache.uri in Hibernate ?
Yes indeed.

> If yes, for which reason have you done that and does it workaround the issue if you remove that property?
For the possibility to load this from a different location, but it is not really needec at that point of time. Removing the property gives me the expected results in javamelody (Cache entries are finally visible).

Of course this does not yet influence the application level cache I also have in place. For this I can not omit the custom URI.

So I think my observations are basically in line with @gtricot 's.

**Comment by evernat** [comment] 2019-07-25 22:39
javamelody can't find reliably the URIs used for CacheManager, when the default CacheManager is not used.
In this case the clear button and the link to cache keys are now hidden (071032c). To be released in 1.79 soon. But those caches are still displayed with efficiency ratio, based on MBeans.

What would be needed is a method getCacheManagers() in javax.cache.spi.CachingProvider to list the known cache managers like it is already possible to list the known caching providers and the known entries of a cache.
The need to be able to clear all the caches from the application justifies the method getCacheManagers() in my opinion. An application would need that after a synchronization of its database with another database for example.

**Comment by stolp** [comment] 2019-07-28 17:38
I tested the 1.79 release and the behavior is now as described above. Too bad that the API is not capable of what would be needed here, I agree that there is something missing here. Thanks for looking into this.

**Comment by evernat** [comment] 2019-09-17 23:27
I have asked to add `CachingProvider.getCacheManagers()` in the JCache api (issue 409 in https://github.com/jsr107/jsr107spec).

But releases of the JCache api were (https://jcp.org/en/jsr/detail?id=107):
- 1.1.1 in Mar, 2019 (maintenance release)
- 1.1.0 in Dec, 2017 (maintenance release)
- 1.0 in Mar, 2014

I would not bet on a major release with api changes soon.
I would not bet on the getCacheManagers() issue resolved in this major release either.

While waiting for the `CachingProvider.getCacheManagers()` method, the clear button and the link to cache keys will certainly stay hidden, when the default CacheManager is not used in the application.

Closing this issue as fixed since those caches are displayed since 1.79 with efficiency ratio, based on MBeans, and we can't do more at the moment.

**Closed by evernat** 2019-09-17 23:27 UTC

**Comment by NicolasFelix** [comment] 2021-07-07 15:14
FYI (_I know this issue is closed for a while now ;), but some can find this usefull_),
by setting the system property **ehcache.jsr107.config.default** to my **ehcore.xml file**,
I've got my caches' list and detail pages displayed as expected/described in that ticket.

This prevents the "default" one (_urn:X-ehcache:jsr107-default-config_ to be loaded)

**Comment by stolp** [comment] 2021-07-07 22:39
Thanks, @NicolasFelix, I tried this, and it is working! 

Of course, since I have two different cache configurations active, I have to decide which one I like to see in JavaMelody.

Much appreciated!

**Comment by maks1212** [comment] 2024-01-04 21:01
@stolp @NicolasFelix can you please explain it more detailed? Ive the same problem usein javamelody 2 ehcache 3 in spring boot 3. cache is shown but cannot delete it? Thanks

**Comment by susp248** [comment] 2024-01-04 21:32
@maks1212 You simply will not be able to get the delete buttons shown with ehcache3 as long as a fixed Cache API is released (probably never).

By explicitly setting the system property **ehcache.jsr107.config.default** to the location of your EHCache configuration file (**ehcore.xml**) you will at least see the cache statistics.

**Comment by maks1212** [comment] 2024-01-05 18:51
Thanks i got it. I misunderstood your comment.
