### ISSUE TITLE
Upgrade Javamelody with jboss server 6.4

### ISSUE THREAD

**Issue by amicos** [javamelody/javamelody#856] opened 2019-08-21 12:33 UTC
**Hello,
We have a problem in our application. We can’t upgrade javamelody to a last version (We can’t launch the server), we have the forward problem.
We use Jboss 6.4 and javamlody 1.61 and we want to upgrade the Javamelody to version 1.79
there are a conflict of dependences between lib we have in javamelody and jboss
Do you have any idea to resolve this problem? Thanks**

`[org.jboss.modules] (MSC service thread 1-8) Failed to define class net.bull.javamelody.MonitoredWithAnnotationPointcut$MonitoredMethodMatcher in Module "deployment.rr-5.0.0-SNAPSHOT.ear.rr-services.war:main" from Service Module Loader: java.lang.LinkageError: Failed to link net/bull/javamelody/MonitoredWithAnnotationPointcut$MonitoredMethodMatcher (Module "deployment.rr-5.0.0-SNAPSHOT.ear.rr-services.war:main" from Service Module Loader)
	at org.jboss.modules.ModuleClassLoader.defineClass(ModuleClassLoader.java:487) [jboss-modules.jar:1.3.6.Final-redhat-1]
	at org.jboss.modules.ModuleClassLoader.loadClassLocal(ModuleClassLoader.java:277) [jboss-modules.jar:1.3.6.Final-redhat-1]
	at org.jboss.modules.ModuleClassLoader$1.loadClassLocal(ModuleClassLoader.java:92) [jboss-modules.jar:1.3.6.Final-redhat-1]
	at org.jboss.modules.Module.loadModuleClass(Module.java:568) [jboss-modules.jar:1.3.6.Final-redhat-1]
	at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:205) [jboss-modules.jar:1.3.6.Final-redhat-1]
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:459) [jboss-modules.jar:1.3.6.Final-redhat-1]
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassChecked(ConcurrentClassLoader.java:408) [jboss-modules.jar:1.3.6.Final-redhat-1]
	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:389) [jboss-modules.jar:1.3.6.Final-redhat-1]
	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:134) [jboss-modules.jar:1.3.6.Final-redhat-1]
	at org.jboss.as.weld.WeldModuleResourceLoader.classForName(WeldModuleResourceLoader.java:68) [jboss-as-weld-7.5.0.Final-redhat-21.jar:7.5.0.Final-redhat-21]
	at org.jboss.weld.bootstrap.BeanDeployer.loadClass(BeanDeployer.java:109) [weld-core-1.1.28.Final-redhat-1.jar:1.1.28.Final-redhat-1]
	at org.jboss.weld.bootstrap.BeanDeployer.addClass(BeanDeployer.java:79) [weld-core-1.1.28.Final-redhat-1.jar:1.1.28.Final-redhat-1]
	at org.jboss.weld.bootstrap.BeanDeployer.addClasses(BeanDeployer.java:137) [weld-core-1.1.28.Final-redhat-1.jar:1.1.28.Final-redhat-1]
	at org.jboss.weld.bootstrap.BeanDeployment.createBeans(BeanDeployment.java:184) [weld-core-1.1.28.Final-redhat-1.jar:1.1.28.Final-redhat-1]
	at org.jboss.weld.bootstrap.WeldBootstrap.deployBeans(WeldBootstrap.java:349) [weld-core-1.1.28.Final-redhat-1.jar:1.1.28.Final-redhat-1]
	at org.jboss.as.weld.WeldStartService.start(WeldStartService.java:63) [jboss-as-weld-7.5.0.Final-redhat-21.jar:7.5.0.Final-redhat-21]
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1980)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1913)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [rt.jar:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [rt.jar:1.8.0_151]
	at java.lang.Thread.run(Thread.java:748) [rt.jar:1.8.0_151]
Caused by: java.lang.NoClassDefFoundError: org/springframework/aop/MethodMatcher
	at java.lang.ClassLoader.defineClass1(Native Method) [rt.jar:1.8.0_151]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763) [rt.jar:1.8.0_151]
	at org.jboss.modules.ModuleClassLoader.doDefineOrLoadClass(ModuleClassLoader.java:361) [jboss-modules.jar:1.3.6.Final-redhat-1]
	at org.jboss.modules.ModuleClassLoader.defineClass(ModuleClassLoader.java:482) [jboss-modules.jar:1.3.6.Final-redhat-1]
	... 20 more
Caused by: java.lang.ClassNotFoundException: org.springframework.aop.MethodMatcher from [Module "deployment.rr-5.0.0-SNAPSHOT.ear.rr-services.war:main" from Service Module Loader]
	at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:213) [jboss-modules.jar:1.3.6.Final-redhat-1]
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:459) [jboss-modules.jar:1.3.6.Final-redhat-1]
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassChecked(ConcurrentClassLoader.java:408) [jboss-modules.jar:1.3.6.Final-redhat-1]
	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:389) [jboss-modules.jar:1.3.6.Final-redhat-1]
	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:134) [jboss-modules.jar:1.3.6.Final-redhat-1]
	... 24 more

12:58:53,388 INFO  [org.jboss.weld.ClassLoading] (MSC service thread 1-8) WELD-000119 Not generating any bean definitions from net.bull.javamelody.MonitoredWithAnnotationPointcut$MonitoredMethodMatcher because of underlying class loading error
12:58:53,389 WARN  [org.jboss.modules] (MSC service thread 1-8) Failed to define class net.bull.javamelody.SpringMongoDbFactoryBeanPostProcessor in Module "deployment.
`

**Comment by evernat** [comment] 2019-08-22 15:59
Note that JBoss 6.4 is very old.
One issue seems to be that when using Weld in JBoss 6.4, it says `ClassNotFoundException: org.springframework.aop.MethodMatcher`, so adding a version of the spring-aop jar may help. But I am not sure that it is an issue blocking the start of the server.

And I think that there are other logs before or after what you have given and which are more informative of why the server does not start. Can you give more complete logs before and after that ?

**Comment by amicos** [comment] 2019-08-23 08:49
yes, we have this error 
 ERROR [org.jboss.msc.service.fail] (MSC service thread 1-8) MSC000001: Failed to start service jboss.deployment.unit."rrr-5.0.0-SNAPSHOT.ear".WeldStartService: org.jboss.msc.service.StartException in service jboss.deployment.unit."rrr-5.0.0-SNAPSHOT.ear".WeldStartService: Failed to start service
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1936) [jboss-msc-1.1.5.Final-redhat-1.jar:1.1.5.Final-redhat-1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [rt.jar:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [rt.jar:1.8.0_151]
	at java.lang.Thread.run(Thread.java:748) [rt.jar:1.8.0_151]
Caused by: org.jboss.weld.exceptions.DeploymentException: **WELD-000069 An interceptor must have at least one binding, but net.bull.javamelody.MonitoringAsynchronousCdiInterceptor has none**
	at org.jboss.weld.bean.InterceptorImpl.<init>(InterceptorImpl.java:72)
	at org.jboss.weld.bean.InterceptorImpl.of(InterceptorImpl.java:59)
	at org.jboss.weld.bootstrap.AbstractBeanDeployer.createInterceptor(AbstractBeanDeployer.java:229)
	at org.jboss.weld.bootstrap.BeanDeployer.createBeans(BeanDeployer.java:151)
	at org.jboss.weld.bootstrap.BeanDeployment.createBeans(BeanDeployment.java:204)
	at org.jboss.weld.bootstrap.WeldBootstrap.deployBeans(WeldBootstrap.java:349)
	at org.jboss.as.weld.WeldStartService.start(WeldStartService.java:63)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1980) [jboss-msc-1.1.5.Final-redhat-1.jar:1.1.5.Final-redhat-1]
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1913) [jboss-msc-1.1.5.Final-redhat-1.jar:1.1.5.Final-redhat-1]

**Comment by evernat** [comment] 2019-08-24 00:45
There was a CDI issue with MonitoringAsynchronousCdiInterceptor and it was fixed in v1.76.0 by removing MonitoringAsynchronousCdiInterceptor from META-INF/beans.xml:
https://github.com/javamelody/javamelody/commit/406639bef141fec249a75fb15c79f0c1ef922d51
So I don't understand what is going on with WELD/CDI in jboss 6.4 when you said you are now using v1.79.0.
Anyway what is going on with WELD/CDI in jboss 6.4 is obsolete  for a long time and it is working correctly in recent versions. So if there is an issue with javamelody in jboss 6.4, it will not be fixed.
You may want to upgrade jboss or perhaps to remove net.bull.javamelody.MonitoringAsynchronousCdiInterceptor class from the javamelody-core jar file.

**Closed by evernat** 2019-08-24 00:45 UTC
Labels: invalid

**Comment by amicos** [comment] 2019-08-26 08:46
thanks

**Comment by venkatpurns** [comment] 2020-10-21 07:41
we are facing issue updating Java melody latest version 1.86 in application . we are using JBoss 6.4 EAP server for our application . we have already tried all the solution mentioned in thread but  its not working 
Current version 1.65 working fine.
https://github.com/javamelody/javamelody/issues/688
As per above link they have confirmed  ,Above 1.65 java melody version will not support Jboss 6.4 server .  Please confirm
whether we have any other possibility  to add this latest JAR

**Comment by evernat** [comment] 2020-10-28 17:15
@venkatpurns 
Yes, what is going on with WELD/CDI in jboss 6.4 is obsolete for a long time and it is working correctly in recent versions. So if there is an issue with javamelody in jboss 6.4, it will not be fixed.
You may want to upgrade jboss. It is possible that removing the net.bull.javamelody.MonitoringAsynchronousCdiInterceptor class from the javamelody-core jar file by yourself would workaround the issue.
