### ISSUE TITLE
enhancement in 1.73.0 greatly reduces reporting granularity

### ISSUE THREAD

**Issue by ceyates** [javamelody/javamelody#754] opened 2018-06-29 15:26 UTC
After upgrading my application to 1.73.0, what were once hundreds of requests reported in the "Statistics http" section are now reduced to a single one under "/\*\*/\*.html".  Reverting to 1.72.0 restores these listings.  "/\*\*/\*.html" is the @RequestMapping used by a controller that dispatches requests that create most html documents served by this application.

Due to "Enhancement: When using Spring MVC, use path from @RequestMapping annotations as http request name, in order to reduce the need of http-transform-pattern parameter (242fb14)"

**Comment by evernat** [comment] 2018-06-29 22:08
I understand your issue when you use a generic path like `@RequestMapping("/**/*.html")`. But it was the point of the enhancement to aggegrate requests like "/people/1" , "/people/2", ..., "/people/1000" to "/people/{id}" in the statistics, when there is a path like `@RequestMapping("/people/{id}")` and without having to use the javamelody parameter `http-transform-pattern`.

At the moment, I am not sure of what I will do for you.

**Comment by evernat** [comment] 2018-07-21 16:53
I suppose that this issue is won't fix given that it works as intended.

**Closed by evernat** 2018-07-21 16:53 UTC
